#!/bin/bash

#$Revision:001$
#$Fri Oct 5 16:22 IST 2023$

#Variables

BASE=/c/Users/Somya/Desktop
DAYS=10
DEPTH=1
SIZE=20MB
RUN=0

#check if the directory is present or not

if [ ! -d $BASE]
then 
   echo "directory does not exist: $BASE"
   exit 1

fi

#create an archive folder if not present

if [! -d $BASE/archive ]
 then 
     mkdir $BASE/archive

fi

#find files larger than size

for i in `find $BASE -maxdepth $DEPTH -type f -size +$SIZE`
do
   
   if[ $RUN -eq 0]
   then 
       echo "[ $(date "+%Y-%m-%d %H:%M:%S")] archiving $i ==>$BASE/archive"
       gzip $i || exit 1
       mv $i.gz $BASE/archive || exit 1

    fi

done






